config/routes.rb
Rails.application.routes.draw do

  resources :people
  root 'people#index'
  get 'people-backend' => 'people#backend_index', :as => "backend_people_index"
  post '/ajax_upload_person_attributes' => 'person_attributes#upload_columns', :as => "upload_person_attributes"

end

app/models/person.rb
class Person < ActiveRecord::Base
end

app/models/person_attribute.rb
class PersonAttribute < ActiveRecord::Base

  scope :active, -> { where(:active => true) }

  ID = "id"

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/people_controller.rb
class PeopleController < ApplicationController
  before_action :set_person, only: [:show, :edit, :update, :destroy]

  # GET /people
  # GET /people.json
  def index
    @person_attribute = PersonAttribute.all
  end

  # GET /people-backend.json
  def backend_index
    respond_to do |format|
      format.json { render json: PersonDatatable.new(view_context) }
    end
  end

  # GET /people/1
  # GET /people/1.json
  def show
  end

  # GET /people/new
  def new
    @person = Person.new
  end

  # GET /people/1/edit
  def edit
  end

  # POST /people
  # POST /people.json
  def create
    @person = Person.new(person_params)

    respond_to do |format|
      if @person.save
        format.html { redirect_to @person, notice: 'Person was successfully created.' }
        format.json { render :show, status: :created, location: @person }
      else
        format.html { render :new }
        format.json { render json: @person.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /people/1
  # PATCH/PUT /people/1.json
  def update
    respond_to do |format|
      if @person.update(person_params)
        format.html { redirect_to @person, notice: 'Person was successfully updated.' }
        format.json { render :show, status: :ok, location: @person }
      else
        format.html { render :edit }
        format.json { render json: @person.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /people/1
  # DELETE /people/1.json
  def destroy
    @person.destroy
    respond_to do |format|
      format.html { redirect_to people_url, notice: 'Person was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_person
      @person = Person.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def person_params
      params[:person].permit(:name, :position, :office, :extn, :start_date, :salary)
    end
end

app/controllers/person_attributes_controller.rb
class PersonAttributesController < ApplicationController

  # PATCH/PUT /ajax_upload_person_attributes
  def upload_columns
    columns = params[:col].keys if params[:col]
    if columns && columns!=[]
      PersonAttribute.update_all(:active=>false)
      PersonAttribute.where(:id => columns).update_all(:active=>true)
    end
    respond_to do |format|
      format.html { redirect_to people_url, notice: 'Columns was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/people_helper.rb
module PeopleHelper
end

app/helpers/person_attributes_helper.rb
module PersonAttributesHelper
end

app/views/layouts/application.html.haml
%html(lang="en")
  %head
    %meta(charset="utf-8")
    %meta(http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1")
    %meta(name="viewport" content="width=device-width, initial-scale=1.0")
    %title= h(@title||="OracleAjaxDatatable")
    = csrf_meta_tags
    = stylesheet_link_tag "application", :media => "all"


  %body{:'data-controller' => controller.controller_path, :'data-action' => controller.action_name }
    .container
      = yield
    = javascript_include_tag "application"

app/views/people/_form.html.haml
= form_for @person, :html => {:class => "form-horizontal"} do |f|

  - if @person.errors.any?
    .alert.alert-danger#error_explanation
      %h2= "#{pluralize(@person.errors.count, "error")} prohibited this person from being saved:"
      %ul
        - @person.errors.full_messages.each do |msg|
          %li= msg

  .form-group
    = f.label :name, "Name", :class => 'col-sm-2 control-label'
    .col-sm-5
      = f.text_field :name, :class => "form-control", :autocomplete => 'off', :required => true

  .form-group
    = f.label :position, "Position", :class => 'col-sm-2 control-label'
    .col-sm-5
      = f.text_field :position, :class => "form-control", :autocomplete => 'off', :required => true

  .form-group
    = f.label :office, "Office", :class => 'col-sm-2 control-label'
    .col-sm-5
      = f.text_field :office, :class => "form-control", :autocomplete => 'off', :required => true

  .form-group
    = f.label :extn, "Extn", :class => 'col-sm-2 control-label'
    .col-sm-5
      = f.text_field :extn, :class => "form-control", :autocomplete => 'off', :required => true

  .form-group
    = f.label :start_date, "Star Date", :class => 'col-sm-2 control-label'
    .col-sm-5
      = f.text_field :start_date, :class => "form-control datepicker", :autocomplete => 'off', :required => true

  .form-group
    = f.label :salary, "Salary", :class => 'col-sm-2 control-label'
    .col-sm-5
      = f.text_field :salary, :class => "form-control", :autocomplete => 'off', :required => true

  .form-group
    .col-sm-offset-2
      = f.submit "Save", :class => 'btn btn-primary'
      = link_to "Cancel", root_url, :class => 'btn btn-default'

app/views/people/edit.html.haml
.page-header
  %h1 Editing person

= render 'form'

app/views/people/index.html.haml
.page-header
  .pull-right
    =link_to 'New', new_person_path, :class => "btn btn-primary"
    =link_to 'Columns', "#", :class => "btn btn-default open-modal", :'data-modal-target' => '#twi_person_attributes_list'
  %h1 Listing people

%table.table.table-condensed.table-hover.table-bordered.datatable-serverside{:'data-source'=>backend_people_index_path(format: :json)}
  %thead
    %tr
      -@person_attribute.active.pluck(:column).each do |column|
        %th=t(column)
  %tbody


=render :partial => "person_attributes/modal_filter"

app/views/people/new.html.haml
.page-header
  %h1 New person

= render 'form'

app/views/people/show.html.haml
.page-header
  .pull-right
    =link_to 'Index', people_path, :class => "btn btn-default"
    =link_to 'New', new_person_path, :class => "btn btn-primary"
    =link_to 'Edit', edit_person_path(@person), :class => "btn btn-warning"
    =link_to 'Delete', @person, :class => "btn btn-danger"
  %h1=@person.name

%dl.dl-horizontal
  %dt Name
  %dd=@person.name
%dl.dl-horizontal
  %dt Position
  %dd=@person.position
%dl.dl-horizontal
  %dt Office
  %dd=@person.office
%dl.dl-horizontal
  %dt Extn
  %dd=@person.extn
%dl.dl-horizontal
  %dt Start Date
  %dd=@person.start_date
%dl.dl-horizontal
  %dt Salary
  %dd=@person.salary
%dl.dl-horizontal

app/views/person_attributes/_modal_filter.html.haml
#twi_person_attributes_list.modal.fade
  .modal-dialog
    .modal-content
      =form_tag upload_person_attributes_path :'data-remote' => true, :'data-type' => 'html' do
        .modal-header
          %button.close{:type => "button", "data-dismiss" => "modal"} ×
          %h3 Columns
        .modal-body
          %h4 Select column to show
          .list-unstyled
            - @person_attribute.each do |attribute|
              .col-sm-offset-1
                %li
                  %label.checkbox-inline
                    -if attribute.column!=PersonAttribute::ID
                      = check_box_tag "col[#{attribute.id}]", true, attribute.active
                    -else
                      = check_box_tag "col[#{attribute.id}]", true, true, :checked => "checked", :onclick => "return false"
                    %span
                      =attribute.column

        .modal-footer
          =submit_tag "Update", :class=>"btn btn-primary"